<?php

return [
    "name" => "page",
    "title" => "Pagina's",
    "description" => "Pagina's module",
    "module_name" => [
        "single" => "Pagina",
        "multiple" => "Pagina's"
    ],
    "tabtitle" => "title",
    "type" => "module",
    "active" => true,
    "locale" => "nl",
    "data" => [],
    "sort" => 999,
    "route" => null,
    "url" => null,
    "icon" => null,
    "rights" => null,
    "tab_title" => "title",
    "ereg" => [],
    "settings" => [],
    "fields" => [
        "uploads" => [
            "active" => true,
            "type" => "",
            "title" => "Uploads",
            "read" => false,
            "required" => false,
            "edit" => false,
        ],
        "locale" => [
            "active" => true,
            "type" => "text",
            "title" => "Taal",
            "read" => true,
            "required" => false,
            "edit" => false,
        ],
        "homepage" => [
            "active" => false,
            "type" => "checkbox",
            "title" => "Homepage",
            "read" => true,
            "read_type" => "bool",
            "required" => false,
            "edit" => true,
        ],
        "locked" => [
            "active" => true,
            "type" => "checkbox",
            "title" => "Vergrendeld",
            "read" => true,
            "read_type" => "bool",
            "required" => false,
            "edit" => true,
        ],
        "fullpage" => [
            "active" => true,
            "type" => "checkbox",
            "title" => "Fullpage",
            "read" => true,
            "read_type" => "bool",
            "required" => false,
            "edit" => true,
        ],
        "template" => [
            "active" => true,
            "type" => "select",
            "title" => "Template",
            "read" => true,
            "required" => true,
            "edit" => true,
        ],
        "description" => [
            "active" => true,
            "type" => "text",
            "title" => "Omschrijving",
            "read" => true,
            "required" => true,
            "edit" => true,
        ],
        "title" => [
            "active" => true,
            "type" => "text",
            "title" => "Titel",
            "read" => true,
            "required" => true,
            "edit" => true,
        ],
        "option_1" => [
            "active" => true,
            "type" => "checkbox",
            "title" => "Policy",
            "read" => true,
            "required" => false,
        ],
        "option_2" => [
            "active" => false,
            "type" => "checkbox",
            "title" => "option_2",
            "read" => true,
            "required" => false,
        ],
        "option_3" => [
            "active" => false,
            "type" => "checkbox",
            "title" => "option_3",
            "read" => true,
            "required" => false,
        ],
        "option_4" => [
            "active" => false,
            "type" => "checkbox",
            "title" => "option_4",
            "read" => true,
            "required" => false,
        ],
        "title_2" => [
            "active" => true,
            "type" => "text",
            "title" => "Subtitel",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "title_3" => [
            "active" => false,
            "type" => "text",
            "title" => "Link beschrijving",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "title_4" => [
            "active" => false,
            "type" => "text",
            "title" => "Subtitel",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "slug" => [
            "active" => true,
            "type" => "text",
            "title" => "Slug",
            "read" => true,
            "required" => true,
            "edit" => true,
        ],
        "seo_title" => [
            "active" => true,
            "type" => "text",
            "title" => "SEO titel",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "seo_description" => [
            "active" => true,
            "type" => "textarea",
            "title" => "SEO omschrijving",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "route" => [
            "active" => true,
            "type" => "routes",
            "title" => "Link",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "route_title" => [
            "active" => true,
            "type" => "text",
            "title" => "Link titel",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "tags" => [
            "active" => false,
            "type" => "textarea",
            "title" => "Tags",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "excerpt" => [
            "active" => true,
            "type" => "textarea",
            "title" => "Inleiding",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "content" => [
            "active" => true,
            "type" => "tinymce",
            "title" => "Bericht",
            "read" => true,
            "required" => false,
            "edit" => true,
        ]
    ]
];
